/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BButton {
        /**
          * The listener for button
         */
        "callback"?: {
    type: string,
    listener: (eventRaised?: UIEvent) => void,
    capture?: boolean
  };
        /**
          * The primary button
         */
        "primary": boolean;
        /**
          * The button title
         */
        "titleBtn": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLBButtonElement extends Components.BButton, HTMLStencilElement {
    }
    var HTMLBButtonElement: {
        prototype: HTMLBButtonElement;
        new (): HTMLBButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "b-button": HTMLBButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface BButton {
        /**
          * The listener for button
         */
        "callback"?: {
    type: string,
    listener: (eventRaised?: UIEvent) => void,
    capture?: boolean
  };
        /**
          * The primary button
         */
        "primary"?: boolean;
        /**
          * The button title
         */
        "titleBtn"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "b-button": BButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "b-button": LocalJSX.BButton & JSXBase.HTMLAttributes<HTMLBButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
